.TH ve-veconfig 5 "9 Oct 2003" "Virtuozzo" "Virtual Private Servers"
.SH NAME
ve-veconfig \- vzctl helper script for setting various VE parameters
.SH SYNOPSIS
/etc/sysconfig/vz-scripts/ve-veconfig 
.SH DESCRIPTION
The \fBve-veconfig\fR script is called by \fBvzctl(8)\fR. Its purpose is
to set various parameters for a given VE.
.SH OPTIONS
Parameters  are  passed to the script in the form of environment variables.
The following variables can be defined:
.IP "\fBHOSTNM\fR
Sets VE hostname to be \fIname\fR.
This is done by modifying VE's \f(CW/etc/hosts\fR and
\f(CW/etc/sysconfig/network\fR (in RedHat or RedHat-like based VE) or
\f(CW/etc/rc.config\fR (in SuSE-based VE).
.IP "\fBSEARCHDOMAIN\fR"
Sets VE resolver's search list for host-name lookup.
This option modifies VE's \f(CW/etc/resolv.conf\fR.
.IP "\fBNAMESERVER\fR
Sets VE name server IP address.
This option modifies VE's \f(CW/etc/resolv.conf\fR.
.IP "\fBUSERPW\fR \fIuser:password\fR"
Sets the \fIpassword\fR for \fIuser\fR, adding \fIuser\fR if it does not
already exists. Several \fB--userpasswd\fR options can be given.
.P
.IP "\fBDIST\fR"
Name of the distribution this VE runs (like \fBredhat-7.1\fR). Used for script
to do distribution-dependent setup.
.P
.SH DIAGNOSTICS
The script is expected to return 0 on success, any other return code
will be printed by \fBvzctl\fR.
.SH SEE ALSO
.BR vzctl (8),
.BR resolv.conf (5).
.SH COPYRIGHT
Copyright (C) 2001-2006, SWsoft. Licensed under GNU GPL.
