.\" $Id: vzcfgvalidate.8,v 1.5.10.6 2005/10/17 11:42:42 igor Exp $
.TH vzcfgvalidate 8 "10 Aug 2005" "OpenVZ" "Virtual Private Server"
.SH NAME
vzcfgvalidate \- validate the VPS configuration file
.SH SYNOPSIS
vzcfgvalidate [\fB-r\fR | \fB-i\fR] \fIconfigfile\fR
.SH OPTIONS
.TP
\fB-r\fR
Repair mode.
.TP
\fB-i\fR
Interactive repair mode.
.SH DESCRIPTION
This utility checks validity of resource control parameters in VPS config file
\fIconfigfile\fR.  Configurations where resources allowed for Virtual
Private Server exceeds system capacity are not valid and dangerous
from stability point of view.

There are three severity levels in output: Error, Warning, Recommendation.
.SH DIAGNOSTICS
Normally, exit status is 0. On program execution error, exit status is 1.
If validation failed exit status is 2.
.SH SEE ALSO
.BR vps.conf (5).
.SH LICENSE
Copyright (C) 2000-2006, SWsoft. Licensed under GNU GPL.
