.\" $Id: vzcpucheck.8,v 1.4.10.3 2005/09/26 14:58:18 igor Exp $
.TH vzcpucheck 8 "10 Aug 2005" "OpenVZ" "Virtual Private Server"
.SH NAME
vzcpucheck \- shows information about CPU power and utilization.
.SH SYNOPSIS
vzcpucheck [\fI-v\fR]
.SH DESCRIPTION
This script shows information about CPU power and utilization. 
.SH OPTIONS
.IP \fB-v\fR 
Display information for each VPS.
.SH RETURN CODE
Returns 0 upon success.
.SH SEE ALSO
.BR vzctl (8).
.SH LICENSE
Copyright (C) 2000-2005, SWsoft. Licensed under QPL.
