.TH vzcpucheck 8 "12 Sep 2006" "OpenVZ" "Virtual Environments"
.SH NAME
vzcpucheck \- shows information about the CPU power and utilization.
.SH SYNOPSIS
vzcpucheck [\fI-v\fR]
.SH DESCRIPTION
This script outputs information on the CPU power and utilization.
.SH OPTIONS
.IP \fB-v\fR
Display information for each VE.
.SH RETURN CODE
Returns 0 upon success.
.SH SEE ALSO
.BR vzctl (8).
.SH LICENSE
Copyright (C) 2000-2007, SWsoft. Licensed under GNU GPL.
