.TH vzlist 8 "7 Feb 2011" "OpenVZ" "Containers"
.SH NAME
vzlist \- containers listing utility
.SH SYNOPSIS
vzlist [\fB-a\fR|\fB-S\fR] [\fB-n\fR] [\fB-H\fR] \
[\fB-o\fR \fIname\fR[,\fIname\fR...]] [\fB-s\fR [\fB-\fR]\fIname\fR] \
[\fB-h\fR \fIpattern\fR] [\fB-N\fR \fIpattern\fR] [\fB-d\fR \fIpattern\fR] \
[\fICTID\fR [\fICTID\fR ...] | \fB-1\fR]
.PP
vzlist \fB-L\fR
.SH DESCRIPTION
This utility is used for listing containers and their parameters.
By default only running containers are listed.
If one or more \fICTID\fRs are specified, only specified containers are
displayed. CTID of \fB-1\fR is used to output CT IDs only, one per line.
.PP
For the fields that can have many values (e.g. \fBip\fR),
all the values are displayed only for the last (i.e. leftmost) column;
otherwise, only the first value is shown.
.SH OPTIONS
.IP "\fB-a\fR, \fB--all\fR"
List all containers.
.IP "\fB-S\fR, \fB--stopped\fR"
List only not running containers (including the ones with status shown as
\fBmounted\fR or \fBsuspended\fR).
.IP "\fB-n\fR, \fB--name\fR"
Display container names instead of hostnames.
.IP "\fB-H\fR, \fB--no-header\fR"
Suppress displaying the header row.
.IP "\fB-o\fR, \fB--output\fR \fIfield\fR[,\fIfield\fR...]"
Display only the specified \fIfield\fRs (see \fBSTANDARD FIELDS\fR
subsection below).
.IP "\fB-s\fR, \fB--sort\fR [\fB-\fR]\fIfield\fR"
Sort by the value of \fIfield\fR (possible arguments are the same
as for \fB-o\fR). The \fB-\fR before the field name means sorting
in the reverse order.
.SS Output filters
List of CTs can be further filtered using the following options.
For patterns one can use the same wildcards as in shell
(i.e. \fB*\fR, \fB?\fR, and \fB[]\fR).
Note: to avoid expansion of wildcards by the shell, one have to escape
the pattern by either putting it into single quotes (like \fB'a*a'\fR)
or by adding a backslash before the wildcard character (like \fBa\\*a\fR).
.IP "\fB-h\fR, \fB--hostname\fR \fIpattern\fR"
List only containers whose hostnames matches the \fIpattern\fR.
.IP "\fB-N\fR, \fB--name_filter\fR \fIpattern\fR"
List only containers whose names matches the \fIpattern\fR.
.IP "\fB-d\fR, \fB--description\fR \fIpattern\fR"
List only containers with descriptions matching the \fIpattern\fR.
.SS Possible fields
.IP "\fB-L\fR, \fB--list\fR"
list all available format specifiers.
.SS STANDARD FIELDS
These may be used to control both output (\fB-o\fR, \fB--output\fR)
and the sorting order (\fB-s\fR, \fB--sort\fR).
.TS
allbox center;
lB lB
lI l.
Value	Header
_
ctid	CTID
hostname	HOSTNAME
name	NAME
description	DESCRIPTION
ostemplate	OSTEMPLATE
ip	IP_ADDR
status	STATUS
kmemsize	KMEMSIZE
lockedpages	LOCKEDP
privvmpages	PRIVVMP
shmpages	SHMP
numproc	NPROC
physpages	PHYSP
vmguarpages	VMGUARP
oomguarpages	OOMGUARP
numtcpsock	NTCPSOCK
numflock	NFLOCK
numpty	NPTY
numsiginfo	NSIGINFO
tcpsndbuf	TCPSNDB
tcprcvbuf	TCPRCVB
othersockbuf	OTHSOCKB
dgramrcvbuf	DGRAMRRB
numothersock	NOTHSOCK
dcachesize	DCACHESZ
numfile	NFILE
numiptent	NIPTENT
swappages	SWAPP
diskspace	DSPACE
diskinodes	DINODES
laverage	LAVERAGE
uptime	UPTIME
cpulimit	CPULIM
cpuunits	CPUUNI
ioprio	IOP
onboot	ONBOOT
bootorder	BOOTORDER
.TE
.P
For the user beancounter fields above, one can use the following suffixes:
.TS
allbox center;
lB lB lB
lI l l.
Suffix	Header	Description
_
 .m	.M	maxheld
 .b	.B	barrier
 .l	.L	limit
 .f	.F	failcnt
.TE
.P
For the disk quota fields above, one can use the following suffixes:
.TS
allbox center;
lB lB lB
lI l l.
Suffix  Header  Description
_
 .s	.S	softlimit
 .h	.H	hardlimit
.TE
.SH EXAMPLES
\fBvzlist -o ctid,kmemsize,kmemsize.l -s kmemsize\fR
.SH RETURN CODE
Returns 0 upon success.
.SH COPYRIGHT
Copyright (C) 2000-2011, Parallels, Inc. Licensed under GNU GPL.
