.TH vzmemcheck 8 "12 Sep 2006" "OpenVZ" "Virtual Environments"
.SH NAME
vzmemcheck \- utility to display information of node memory parameters.
.SH SYNOPSIS
vzmemcheck [\fB-v\fR] [\fB-A\fR]
.SH OPTIONS
.IP \fB-v\fR 4
Display information for each VE.
.IP \fB-A\fR 4
Display absolute values (in megabytes). 
.SH DESCRIPTION
This utility shows node memory parameters:
\fBlow memory utilization\fR, \fBlow memory commitment\fR, \fBRAM utilization\fR
,\fBmem+swap utilization\fR, \fBmem+swap commitment\fR,
\fBallocmem utilization\fR, \fBallocmem commitment\fR, \fBallocmem limit\fR.
.P
With \fB-A\fR option it show absolute values (in megabytes).
Without \fB-v\fR option, it will be 1 more line: header line(s),
the numerator and the denominator of the corresponding fraction.
.SH DIAGNOSTICS
Normally, exit status is 0. On error, exit status is 1.
.SH LICENSE
Copyright (C) 2000-2007, SWsoft. Licensed under GNU GPL.
