.\" $Id: vzpid.8,v 1.4.10.4 2005/10/17 11:42:42 igor Exp $
.TH vzpid 8 "10 Aug 2005" "OpenVZ" "Virtual Private Server"
.SH NAME
vzpid \- display the VPS id given the process id (pid).
.SH SYNOPSIS
vzpid [\fB-h\fR] [\fIpid\fR [...]]
.SH DESCRIPTION
This script displays the VPS id the process with the given \fIid\fR belongs to.
.SH OPTIONS
.IP \fIpid\fR
The \fIpid\fR of the process to display the VPS id of.
.SH RETURN CODE
Returns 0 upon a successful execution.
.SH SEE ALSO
.BR vzctl (8).
.SH LICENSE
Copyright (C) 2000-2005, SWsoft. Licensed under QPL.
