.\" $Id: vzpid.8,v 1.4.10.3 2005/09/26 14:58:18 igor Exp $
.TH vzpid 8 "10 Aug 2005" "OpenVZ" "Virtual Private Server"
.SH NAME
vzpid \- displays VPS id by process id.
.SH SYNOPSIS
vzpid [\fB-h\fR] [\fIpid\fR [...]]
.SH DESCRIPTION
This script displays VPS id the process with the given \fIid\fR belongs to.
.SH OPTIONS
.IP \fIpid\fR
The \fIpid\fR of the process to display VPS id of.
.SH RETURN CODE
Returns 0 upon success.
.SH SEE ALSO
.BR vzctl (8).
.SH LICENSE
Copyright (C) 2000-2005, SWsoft. Licensed under QPL.
