.TH vzpid 8 "22 Feb 2008" "OpenVZ" "Containers"
.SH NAME
vzpid \- display the CT ID given the process ID (PID).
.SH SYNOPSIS
vzpid [\fB-h\fR] [\fIpid\fR [...]]
.SH DESCRIPTION
This script displays the CT ID the process with the given \fIpid\fR belongs to.
.SH OPTIONS
.IP \fIpid\fR
The \fIpid\fR of the process to display the CT ID of.
.SH RETURN CODE
Returns 0 upon a successful execution.
.SH SEE ALSO
.BR vzctl (8).
.SH LICENSE
Copyright (C) 2000-2008, Parallels, Inc. Licensed under GNU GPL.
