#!/bin/bash
# Copyright (C) 2000-2005 SWsoft. All rights reserved.
#
# This file may be distributed under the terms of the Q Public License
# as defined by Trolltech AS of Norway and appearing in the file
# LICENSE.QPL included in the packaging of this file.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

CONFIG=${1} 
if ! . "$CONFIG"; then 
        echo "can't source interface config $CONFIG" >&2
        exit 1
fi

# VZNET device
vznet=$DEVICE

. /etc/init.d/functions

action $"Shutting down interface $vznet: " \
        ip link set $vznet down


