#!/bin/bash
#  Copyright (C) 2000-2006 SWsoft. All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
# This script setup routing for given VPS.
#
# Parameters are passed in environment variables.
# Required parameters:
#   VEID          - VPS id
# Optional parameters:
#   IP_ADDR       - IP address(es) to add
#                   (several addresses should be divided by space)
#   VE_STATE      - state of VPS; could be one of:
#                     starting | stopping | running | stopped
. /usr/lib/vzctl/scripts/vps-functions

vzcheckvar VEID

######## Common stuff - route, ARP, iptables ###########
# Set routing, iptables, ARP...
vzgetnetdev

vzarpipdetect "$IP_ADDR"
for IP in $IP_ADDR; do
	vzaddrouting $IP
	vzarp add $IP
done
vzarpipset "$IP_ADDR"
# Save ip address information
mkdir -p ${VE_STATE_DIR} >/dev/null 2>&1
if [ "${VE_STATE}" == "starting" ]; then
  echo -n  "${IP_ADDR} " > ${VE_STATE_DIR}/${VEID}
elif [ "${VE_STATE}" == "running" ]; then
  echo -n "${IP_ADDR} " >> ${VE_STATE_DIR}/${VEID}
fi

exit 0
# end of script

